export const contact = {
  email: 'junde.richard@gmail.com',
  github: 'https://github.com/kkho0000',
}

export const messages = {
  'zh-CN': {
    name: '李君德',
    alternateName: 'Junde Li',
    homeLabel: '李君德的个人主页',
    navigation: '主要导航',
    language: '选择语言',
    about: '关于',
    projects: '项目',
    contact: '联系',
    skip: '跳到主要内容',
    introduction: '关注元宇宙、AI 与虚拟现实，也探索数学与医疗数据分析，以及游戏开发与策划。这里记录我的项目与实践。',
    educationTitle: '教育经历',
    education: [
      { school: '北京科技大学', degree: '理学学士 · 信息与计算科学', period: '2020–2024' },
      { school: '香港理工大学', degree: '理学硕士 · 元宇宙科技', period: '2024–2025' },
    ],
    focusTitle: '关注方向',
    focus: [
      { title: '元宇宙、AI 与虚拟现实', description: '探索虚拟空间、人工智能与沉浸式交互，以及它们在数字体验中的应用。' },
      { title: '数学与数据分析', description: '关注数学方法与数据分析，尤其是医疗数据集的整理、探索与理解。' },
      { title: '游戏开发与策划', description: '从玩法与叙事设计，到原型开发与实现，探索游戏如何表达想法。' },
    ],
    selectedWork: '部分项目',
    jumpToProjects: '浏览项目',
    contribution: '我的职责',
    onThisPage: '本页内容',
    nextProject: '下一项目',
    allProjects: '全部项目',
    projectsIntro: '虚拟现实与游戏方向的项目记录。',
    categories: { technology: '元宇宙 / 虚拟现实', games: '游戏开发 / 策划' },
    viewProject: '查看项目',
    imageUnavailable: '封面待补充',
    imageLoadError: '图片暂时无法加载',
    openOriginal: '查看原图',
    portraitAlt: '李君德在山间的留影',
    projectVideo: '项目演示',
    openVideo: '打开视频',
    watchOnYouTube: '在 YouTube 观看',
    playProjectVideo: '播放项目视频',
    loadingProjectVideo: '正在连接 YouTube…',
    videoLoadError: '视频暂时无法播放，请重试或打开视频文件。',
    loadingProjects: '正在加载项目…',
    projectsError: '项目暂时无法加载，请稍后重试。',
    emptyProjects: '暂无项目记录。',
    retry: '重新加载',
    backToProjects: '返回项目',
    projectNote: '项目记录',
    loadingDetail: '正在加载项目内容…',
    detailUnavailable: '暂无详细记录',
    detailPending: '目前可查看项目简介，详细记录待补充。',
    detailErrorTitle: '内容暂时无法加载',
    detailError: '请检查网络连接后重试。',
    projectNotFound: '未找到这个项目',
    projectNotFoundCopy: '这个项目地址不存在，可以返回项目列表继续浏览。',
    browseProjects: '浏览其他项目',
    metaDescription: '李君德的个人主页。关注元宇宙、AI、虚拟现实，数学与医疗数据分析，以及游戏开发与策划。',
  },
  en: {
    name: 'Junde Li',
    alternateName: '李君德',
    homeLabel: 'Junde Li’s personal website',
    navigation: 'Main navigation',
    language: 'Select language',
    about: 'About',
    projects: 'Projects',
    contact: 'Contact',
    skip: 'Skip to main content',
    introduction: 'My interests span the metaverse, AI and virtual reality; mathematics and medical data analysis; and game development and design. This is a collection of my projects and practice.',
    educationTitle: 'Education',
    education: [
      { school: 'University of Science and Technology Beijing (USTB)', degree: 'Bachelor of Science · Information and Computing Science', period: '2020–2024' },
      { school: 'The Hong Kong Polytechnic University (HKPolyU)', degree: 'MSc · Metaverse Technology', period: '2024–2025' },
    ],
    focusTitle: 'Areas of interest',
    focus: [
      { title: 'Metaverse, AI & VR', description: 'Exploring virtual spaces, artificial intelligence and immersive interaction, and their use in digital experiences.' },
      { title: 'Mathematics & data analysis', description: 'An interest in mathematical methods and data analysis, with a focus on organizing, exploring and understanding medical datasets.' },
      { title: 'Game development & design', description: 'From mechanics and narrative to prototyping and implementation, exploring how games can express ideas.' },
    ],
    selectedWork: 'Selected projects',
    jumpToProjects: 'Explore projects',
    contribution: 'My contribution',
    onThisPage: 'On this page',
    nextProject: 'Next project',
    allProjects: 'All projects',
    projectsIntro: 'Project notes on virtual reality and games.',
    categories: { technology: 'Metaverse / VR', games: 'Game development / Design' },
    viewProject: 'View project',
    imageUnavailable: 'Cover to be added',
    imageLoadError: 'Image could not be loaded',
    openOriginal: 'View original',
    portraitAlt: 'Junde Li outdoors in the mountains',
    projectVideo: 'Project demo',
    openVideo: 'Open video',
    watchOnYouTube: 'Watch on YouTube',
    playProjectVideo: 'Play project video',
    loadingProjectVideo: 'Connecting to YouTube…',
    videoLoadError: 'The video could not be played. Try again or open the video file.',
    loadingProjects: 'Loading projects…',
    projectsError: 'Projects could not be loaded. Please try again.',
    emptyProjects: 'No projects yet.',
    retry: 'Try again',
    backToProjects: 'Back to projects',
    projectNote: 'Project notes',
    loadingDetail: 'Loading project notes…',
    detailUnavailable: 'No detailed notes yet',
    detailPending: 'A project overview is available above. Detailed notes are yet to be added.',
    detailErrorTitle: 'Content could not be loaded',
    detailError: 'Please check your connection and try again.',
    projectNotFound: 'Project not found',
    projectNotFoundCopy: 'There is no project at this address. Return to the project list to keep browsing.',
    browseProjects: 'Browse other projects',
    metaDescription: 'Junde Li’s personal website. Metaverse, AI and virtual reality; mathematics and medical data analysis; game development and design.',
  },
}
